# Generated by Django 4.2.7 on 2023-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.BooleanField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
