# Generated by Django 4.2.7 on 2023-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
