# Generated by Django 4.2.7 on 2023-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_customuser_can_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
