# Generated by Django 4.2.7 on 2023-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_customuser_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=''),
        ),
    ]
